---
title: "Importing WFS layers"
author: "Fleur Petersen"
date: "2023-11-17"
output: html_document
---

```{r load-packages}
library(sf)
library(tidyverse) 
library(httr)
library(ows4R) 
library(leaflet)
library(gdalUtilities)
```


```{r clear-memory}
rm(list=ls())
```

```{r function-multisurface-to-multipolygon}
ensure_multipolygons <- function(X) {
    tmp1 <- tempfile(fileext = ".gpkg")
    tmp2 <- tempfile(fileext = ".gpkg")
    st_write(X, tmp1)
    ogr2ogr(tmp1, tmp2, f = "GPKG", nlt = "MULTIPOLYGON")
    Y <- st_read(tmp2)
    st_sf(st_drop_geometry(X), geom = st_geometry(Y))
}
```

# Inladen grenzen Vlaanderen en provincies

```{r boundaries-flanders}
Vlaanderen_grenzen <- st_read("./prius/data/spatial/flanders_wgs84.geojson")
Provincies_grenzen <- st_read("./prius/data/spatial/Provincies.geojson")
```

# Habitatrichtlijndeelgebieden (ps:ps_hbtrl_deel)

```{r get-ps-hbtrl-deel}
wfs_ANB <- "https://www.mercator.vlaanderen.be/raadpleegdienstenmercatorpubliek/wfs"

#generate URL for WFS download
url <- parse_url(wfs_ANB)
url$query <- list(service = "WFS",
                  version = "2.0.0", 
                  request = "GetFeature",
                  typename = "ps:ps_hbtrl_deel")
request <- build_url(url)

ps_hbtrl_deel <- read_sf(request) %>%
  st_set_crs(31370) %>%  # omzetten naar Lambert72
  st_transform("+proj=longlat +datum=WGS84") %>%  #needed for leaflet
  ensure_multipolygons()   # multisurface to multipolygon
```

# Vogelrichtlijngebieden (ps:ps_vglrl)

```{r get-ps-vgrl}
url <- parse_url(wfs_ANB)
url$query <- list(service = "WFS",
                  version = "2.0.0", 
                  request = "GetFeature",
                  typename = "ps:ps_vglrl")
request <- build_url(url)

ps_vglrl <- read_sf(request) %>%
  st_set_crs(31370) %>%  
  st_transform("+proj=longlat +datum=WGS84") %>%  
  ensure_multipolygons()   
```

# Biologische waarderingskaart (BWK:Bwkhab)

## wegens max.van 10.000 features bij inladen WFS,laadt ik de BWK/Natura2000 Habitatkaart in als shapefile

```{r import-shapefile-bwkhab}
bwkhab <- st_read("./radius/data/spatial/BwkHab.shp") %>%
  st_transform("+proj=longlat +datum=WGS84")

# aanpassing bwk/n2000 habitatkaart voor gebruik in RadIUS
bwkhab_adj <- bwkhab %>% 
  mutate(HAB1 = str_sub(bwkhab$HAB1, 1, 4)) %>%  # only retain the first part of the HAB1 string
  group_by(HAB1) %>%                             # summarise df to retain one line per HAB1 value
  summarise() %>%                                    
  filter(grepl('^[0-9]', HAB1))                  # remove non-n2000 habitats
```

# ANB Patrimonium databank (am:am_patdat)

```{r ANB patrimonium databank (am:am_patdat)}
url <- parse_url(wfs_ANB)
url$query <- list(service = "WFS",
                  version = "2.0.0", 
                  request = "GetFeature",
                  typename = "am:am_patdat")
request <- build_url(url)

am_patdat <- read_sf(request) %>%
  st_set_crs(31370) %>%  
  st_transform("+proj=longlat +datum=WGS84") %>%  
  ensure_multipolygons()   
```

# Natuurbeheerplannen (ps:ps_nbhp)

```{r get-ps-nbhp}
url <- parse_url(wfs_ANB)
url$query <- list(service = "WFS",
                  version = "2.0.0", 
                  request = "GetFeature",
                  typename = "ps:ps_nbhp")
request <- build_url(url)

ps_nbhp <- read_sf(request) %>%
  st_set_crs(31370) %>%  
  st_transform("+proj=longlat +datum=WGS84") %>%  
  ensure_multipolygons()   
```
