---
title: "RadIUS dashboard (try-out)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source_code: embed 
    theme: 
      version: 4
    runtime: shiny
---

```{r libraries, include=FALSE}
# dashboard packages
library(flexdashboard)
library(shiny)

# overige packages
library(sf)
library(tidyverse)
library(ows4R) 
library(magrittr)
library(gtools)

#visualisatie packages
library(plotly) 
library(leaflet)

wd <- "~/Github/prius-radius/" 
```

```{r get-provincie-grenzen, include=FALSE}
Provincies_grenzen <- st_read(paste0(wd,"prius/data/spatial/Provincies.geojson"))
```

```{r get-wfs-data, include=FALSE}
ps_hbtrl_deel <- st_read(paste0(wd,"radius/data/spatial/ps_hbtrl_deel.shp")) %>%
  mutate(code = gebcode) %>%
  st_transform(4326)
ps_vglrl <- st_read(paste0(wd,"radius/data/spatial/ps_vglrl.shp")) %>%
  mutate(code = na2000code, naam = gebnaam) %>%
  st_transform(4326)
am_patdat <- st_read(paste0(wd,"radius/data/spatial/am_patdat.shp")) %>%
  mutate(code = regio, naam = regio) %>%
  st_transform(4326)
ps_nbhp <- st_read(paste0(wd,"radius/data/spatial/ps_nbhp.shp")) %>%
  mutate(code = egndmty, naam = egndmty) %>%
  st_transform(4326) 
bwkhab_adj <- st_read(paste0(wd,"radius/data/spatial/bwkhab_adj.shp")) %>%
  mutate(code = HAB1, naam = HAB1) %>%
  st_transform(4326)

# wfs data samenvoegen in lijst
list_wfs <- list("Habitatrichtlijn" = ps_hbtrl_deel, "Vogelrichtlijn" = ps_vglrl, "ANB Patrimonium" = am_patdat, "Natuurbeheerplannen" = ps_nbhp, "BWK Habitatkaart" = bwkhab_adj)
```

```{r get-occ-flanders, include=FALSE}
occ_flanders <- read.csv(paste0(wd,"radius/data/input/gbif_occ_flanders.csv")) %>%
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = "+proj=longlat +datum=WGS84") %>%
  arrange(Soort, .locale="en") # sorteer volgens soortnaam, onafhankelijk van hoofdletters
```

```{r get-metric-data, include=FALSE}
HBTRL <- read.csv(paste0(wd,"radius/data/output/HBTRL.csv"))
VGLRL <- read.csv(paste0(wd,"radius/data/output/VGLRL.csv")) 
PATDAT <- read.csv(paste0(wd,"radius/data/output/PATDAT.csv")) 
NBHP <- read.csv(paste0(wd,"radius/data/output/NBHP.csv")) 
BWKHAB <- read.csv(paste0(wd,"radius/data/output/BWKHAB.csv")) 
TOP3 <- read.csv(paste0(wd,"radius/data/output/TOP3.csv"))

# metrics dfs samenvoegen in lijst
list_metrics <- list("Habitatrichtlijn" = HBTRL, "Vogelrichtlijn" = VGLRL, "ANB Patrimonium" = PATDAT, "Natuurbeheerplannen" = NBHP, "BWK Habitatkaart" = BWKHAB)
```


Home
=====================================

Row
-------------------------------------
### **Welkom bij de RadIUS dashboard**

*(voorbeeld van welkomstpagina o.b.v. RIPARIAS dashboard)*

Dit dashboard verzamelt het werk uitgevoerd onder het [RadIUS-project](https://pureportal.inbo.be/en/projects/radius-invasive-alien-species-in-flanders-nature).  

**Data & ontwikkeling** 

De weergegeven verspreidingsdata is publiek beschikbaar via [GBIF](https://www.gbif.org/).

**Soorten**

Soorten in deze analyses komen voort uit de  
*  Unielijst  
*  DUNIAS project soorten  
*  RIPARIAS alert soortenlijst  
*  etc.

**Contact**

Het dashboard wordt onderhouden door het Instituut voor Natuur- en Bosonderzoek (INBO), als onderdeel van het RadIUS-project. Bij vragen of onduidelijkheden kunt u steeds terecht bij faunabeheer@inbo.be


Verspreiding
=====================================

Inputs {.sidebar}
-------------------------------------
```{r inputs-verspreiding}
selectizeInput(inputId = "soort", label = "Soort:", choices = unique(occ_flanders$Soort) , selected = 1)

sliderInput(inputId = "jaar", label = "Periode:", min = 2015, max = 2023, value = c(2015,2023), step = 1, sep = "", dragRange = TRUE)
```


```{r reactieve-elementen-verspreiding}
occ_species <- reactive({
  occ_flanders %>%
    subset(Soort == input$soort & year >= input$jaar[1] & year <= input$jaar[2]) 
  })

occ_sum <- reactive({
  occ_species() %>%
    st_drop_geometry() %>%
    count(year, name = "obs") %>%
    right_join(data.frame(year = 2015:2023), by = "year") %>%
    arrange(year) %>%
    na.replace(0) %>%
    mutate(tot_obs = cumsum(obs))
})

```

Row
-------------------------------------
### Soortnaam {.value-box}
```{r}
renderValueBox({
  naam <- unique(input$soort)
  wetnaam <- unique(occ_species()$Species)

  valueBox(value = naam, caption = wetnaam)
})
```

### GBIF code {.value-box}
```{r}
renderValueBox({
  gbif_code <- unique(occ_flanders[occ_flanders$Soort == input$soort,]$speciesKey)

  valueBox(value = gbif_code, caption = "GBIF code")
})
```

### Total number of observations {.value-box}
```{r}
renderValueBox({
  tot_obs <- nrow(occ_species())

  valueBox(value = tot_obs, caption = "Waarnemingen")
})
```

Row {data-height=50}
-------------------------------------
```{r reactieve-tekst-verspreiding}
renderText({
  paste0("Onderstaande kaart geeft de Vlaamse verspreiding van ", input$soort, " weer tussen ", input$jaar[1], " en ", input$jaar[2], ". ", input$kaart, "gebieden worden in groen weergegeven.") 
})
```

Row
-------------------------------------
```{r kaartje-verspreiding}
renderLeaflet({
  leaflet() %>%
    addTiles() %>%
    addPolygons(data = Provincies_grenzen,
                color = "black",
                fillColor = "lightgrey",
                fillOpacity = 0.2,
                weight = 2) %>%
    addCircleMarkers(data = occ_species(),
                     radius = 2,
                     fillOpacity = 1,
                     label = ~paste0('<strong>', Soort, '</strong>',
                                     '<br/>', day, "/", month, "/", year) %>% 
                       lapply(htmltools::HTML))
})
```

Row {.tabset .tabset-fade}
-------------------------------------
**Aantal waarnemingen vs. jaar**

### Absoluut
```{r}
renderPlotly({
  plot_ly() %>%
    add_bars(data = occ_sum(), 
             x = ~as.factor(year), 
             y = ~obs,
             text = ~obs) %>%
    layout(xaxis = list(title = "Jaar"),
           yaxis = list(title = "Aantal waarnemingen"))})
```

### Cumulatief
```{r}
renderPlotly({
  plot_ly() %>%
    add_bars(data = occ_sum(), 
             x = ~as.factor(year), 
             y = ~tot_obs,
             text = ~tot_obs) %>%
    layout(xaxis = list(title = "Jaar"),
           yaxis = list(title = "Aantal waarnemingen"))})
```


Bezetting per soort
=====================================

Inputs {.sidebar}
-------------------------------------
```{r input-bezetting-per-soort}
selectizeInput(inputId = "soort2", label = "Soort:", choices = unique(occ_flanders$Soort) , selected = 1)

radioButtons(inputId = "kaart", label = "Kaart:", choices = c("Habitatrichtlijn", "Vogelrichtlijn", "ANB Patrimonium", "Natuurbeheerplannen", "BWK Habitatkaart"), selected = "Habitatrichtlijn")

sliderInput(inputId = "jaar2", label = "Periode:", min = 2015, max = 2023, value = c(2015,2023), step = 1, sep = "", dragRange = TRUE)

sliderInput("buffer", label = "Bufferafstand:", min = 10, max = 500, value = 1, step = 10)
```

```{r reactieve-elementen-bezetting-soort}
gebied <- reactive({
  list_wfs %>%
    extract2(input$kaart) %>%
    mutate(geb_area = st_area(.)) 
})

occ_species2 <- reactive({
  occ_flanders %>%
    subset(Soort == input$soort2 & year >= input$jaar2[1] & year <= input$jaar2[2]) 
})

occ_buffered <- reactive({
  occ_species2() %>%
    st_transform(31370) %>%
    st_buffer(dist = input$buffer) %>%
    st_union() %>%
    st_cast('POLYGON') %>%
    st_sf() %>%
    st_transform(4326) %>%
    mutate(buf_area = st_area(.))
})

occ_intersection <- reactive({
  occ_buffered() %>%
    st_intersection(gebied()) %>%
    mutate(intersect_area = st_area(.)) %>%
    st_transform(4326)
})

metrics_in_overall <- reactive({
  as.data.frame(
    cbind(
      soort = input$soort2,
      gebied = paste0(c("in", "notin"), input$kaart2),
      perc = format(round(c(
        as.numeric(sum(occ_intersection()$intersect_area) / sum(occ_buffered()$buf_area)), 
        1 - as.numeric(sum(occ_intersection()$intersect_area) / sum(occ_buffered()$buf_area))), 3)),
      area = format(round(c(
        as.numeric(sum(occ_intersection()$intersect_area)),
        as.numeric(sum(occ_buffered()$buf_area) - sum(occ_intersection()$intersect_area))
      )))
  )
)
})

metrics_in_per_gebied <- reactive({
  occ_intersection() %>%
          group_by(code) %>%
          summarise(intersect_area = sum(intersect_area)) %>%
          st_drop_geometry() %>%
          mutate(perc = as.numeric(intersect_area / sum(occ_intersection()$intersect_area))) %>%
          left_join(gebied() %>% st_drop_geometry() %>% select(code, naam) %>% unique(), by = c("code"))
}) 
```

Row
-------------------------------------
```{r kaartje-bezetting}
renderLeaflet({
  if (nrow(occ_species2()) == 0) {
    leaflet() %>%
      addTiles(group = "OSM") %>%
      addPolygons(data = Provincies_grenzen,
                color = "black",
                weight = 2,
                fillColor = "lightgrey",
                fillOpacity = 0.2) %>%
      addPolygons(data = gebied(),
              color =  "green",
              weight = 1,
              fillColor = "green",
              fillOpacity = 0.8, 
              label = ~paste0(naam," (",code, ")"))
  }
  else {
    leaflet() %>%
      addTiles(group = "OSM") %>%
      addPolygons(data = Provincies_grenzen,
                color = "black",
                weight = 2,
                fillColor = "lightgrey",
                fillOpacity = 0.2) %>%
      addPolygons(data = gebied(),
              color =  "green",
              weight = 1,
              fillColor = "green",
              fillOpacity = 0.8, 
              label = ~paste0(naam," (",code, ")")) %>%
      addPolygons(data = occ_buffered(),
                  weight = 1,
                  label = ~paste0("gebufferd opp.: ", round(buf_area,1), " m²")) %>%
      addCircleMarkers(data = occ_species2(),
                       radius = 4,
                       weight = 1,
                       opacity = 1,
                       fillOpacity = 1,
                       label = ~paste0('<strong>', Soort, '</strong>',
                                     '<br/>', day, "/", month, "/", year) %>% 
                         lapply(htmltools::HTML)) %>%
      addPolygons(data = occ_intersection(),
                  color = "red",
                  fillColor = "red",
                  label = ~paste0("overlappend opp.: ", round(intersect_area,1), " m²")) 
  }
})
```

Row {data-height=600}
-------------------------------------
### **Overlap met gebiedstype**
*percentage van verspreiding dat __wel__ (orange) of __niet__ (blauw) overlapt met gebiedstype.*
```{r}
renderPlotly({
    if (nrow(occ_species2()) != 0) {
      plot_ly(metrics_in_overall(),
          labels = ~gebied,
          values = ~perc,
          type = 'pie',
          textposition = "inside",
          textinfo = "percent",
          hoverinfo = "text",
          text = ~paste(area, ' m²'),
          showlegend = FALSE) %>%
    layout(
      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
    }
})

```

### **Percentage van overlap per deelgebied**
*Proportie van totale overlap (oranje op linker pie chart) tussen soort en gebiedstype per deelgebied (inBE2200033, inBE2100016, ...).*
```{r}
renderPlotly({
  plot_ly(metrics_in_per_gebied(),
              labels = ~code,
              values = ~perc,
              type = 'pie',
              textposition = "inside",
              textinfo = "label+percent",
              hoverinfo = "text",
              text = ~paste0(naam, " (", round(intersect_area, 1), " m²)"),
              showlegend = FALSE) %>%
        layout(
          xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
          yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

Bezetting per gebied
=====================================

Inputs {.sidebar}
-------------------------------------
```{r input-bezetting-per-gebied}

```

Row
-------------------------------------
```{r}

```