```{r libraries}
library(sf)
library(leaflet)
library(tidyverse)
library(dplyr)
library(vecsets)
```

```{r clear memory}
rm(list=ls())
```

```{r get species list}
species_list <-  read_csv("./prius2/temp/prius2_list_v25-09-23.csv")

df_prot_areas <- read_tsv(
  "https://raw.githubusercontent.com/trias-project/indicators/master/data/interim/intersect_EEA_ref_grid_protected_areas.tsv",
  na = "")

Natura2000 <-  df_prot_areas %>% filter(natura2000 == TRUE)
spa <- df_prot_areas %>% filter(spa == TRUE)
habitat <- df_prot_areas %>% filter(habitat == TRUE)
```

```{r get shapes}
vla_1km <- st_read("./prius/data/spatial/grids/vla_1km.geojson")
```

```{r update cube locally}
fistools::download_gdrive_if_missing(gfileID = "154S4vww2G1f0vH7_jt1cZJXeUEmXlZaL",
                                     destfile = "prius2/input/prius2_species_cube.csv",
                                     update_always = TRUE,
                                     email = Sys.getenv("email"))
```

```{r get cube data}
IAS_Cube <- read_csv(file = "./prius2/input/prius2_species_cube.csv") %>% 
  as_tibble()

IAS_Cube <- IAS_Cube %>%
  filter(year >= 2015) %>% 
  filter(specieskey %in% species_list$GBIF_code) %>% 
  filter(eeacellcode %in% vla_1km$CELLCODE)
```

```{r test data completeness}
IAS_Cube_summarise <- IAS_Cube %>% 
  group_by(specieskey) %>% 
  summarise(n_tot = sum(occurrences, na.rm = TRUE))

in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "specieskey")) %>% 
  filter(!is.na(n_tot))
```

```{r}
df <- data.frame()

for (species_name in unique(in_cube$soort)){
  
  print(species_name)
  GBIF_codes <- in_cube[which(in_cube$soort==species_name),]$GBIF_code
  print(GBIF_codes)
  IAS_Cube_temp <- IAS_Cube %>%
    filter(specieskey %in% GBIF_codes)

  N_occ_spec <- as.numeric(n_distinct(IAS_Cube_temp$eeacellcode)) # nodig, want zelfde cel voor verschillende jaren
  N_Natura2000 <- as.numeric(n_distinct(Natura2000$CELLCODE))
  N_spa <- as.numeric(n_distinct(spa$CELLCODE))
  N_habitat <- as.numeric(n_distinct(habitat$CELLCODE))
  
  N_occ_spec_in_Natura2000 <- as.numeric(n_distinct(
    IAS_Cube_temp[which(IAS_Cube_temp$eeacellcode %in% Natura2000$CELLCODE),]$eeacellcode))
  N_occ_spec_in_spa <- as.numeric(n_distinct(
    IAS_Cube_temp[which(IAS_Cube_temp$eeacellcode %in% spa$CELLCODE),]$eeacellcode))
  N_occ_spec_in_habitat <- as.numeric(n_distinct(
    IAS_Cube_temp[which(IAS_Cube_temp$eeacellcode %in% habitat$CELLCODE),]$eeacellcode))
                  
df <- rbind(df, data.frame(species_name,
                           N_occ_spec,
                           N_occ_spec_in_Natura2000,
                           N_occ_spec_in_Natura2000/N_occ_spec,
                           N_occ_spec_in_habitat/N_occ_spec,
                           N_occ_spec_in_spa/N_occ_spec,
                           round(100*(N_occ_spec_in_Natura2000/N_occ_spec), digits = 1),  # Idem, as percent (%), for report
                           round(100*(N_occ_spec_in_habitat/N_occ_spec), digits = 1),     # Idem, as percent (%), for report
                           round(100*(N_occ_spec_in_spa/N_occ_spec), digits = 1),         # Idem, as percent (%), for report
                           N_occ_spec_in_Natura2000/N_Natura2000,
                           N_occ_spec_in_habitat/N_habitat,
                           N_occ_spec_in_spa/N_spa,
                           round(1000*(N_occ_spec_in_Natura2000/N_Natura2000), digits = 1), # Idem, as promille (‰), for report
                           round(1000*(N_occ_spec_in_habitat/N_habitat), digits = 1),       # Idem, as promille (‰), for report
                           round(1000*(N_occ_spec_in_spa/N_spa), digits = 1)))              # Idem, as promille (‰), for report
}

colnames(df) <- c("species",
                  
                  "N_occ",
                  "N_occ_in_N2000",
                  
                  "share_in_N2000",
                  "share_in_HRL",           # HRL = Habitatrichtlijn
                  "share_in_VRL",           # VRL = Vogelrichtlijn
                  
                  "%_in_N2000",
                  "%_in_HRL",
                  "%_in_VRL",
                  
                  "share_of_N2000",
                  "share_of_HRL",
                  "share_of_VRL",
                  
                  "‰_of_N2000",
                  "‰_of_HRL",
                  "‰_of_VRL")
```

```{r}
write_csv(df, "./prius2/output/occupancy_Natura2000/occupancy_Natura2000.csv")
```

```{r}
# The only purpose of this chunck is to prepare the data for easy copy-paste into the PrIUS report
helper <- df %>% 
  left_join(species_list, by = c("species" = "soort")) %>% 
  select(species, Species = species_wettelijke_naam,
         `%_in_N2000`, `%_in_HRL`, `%_in_VRL`,
         `‰_of_N2000`, `‰_of_HRL`, `‰_of_VRL`) %>% 
  arrange(Species)

for (soortje in unique(helper$Species)){
  
  A <- subset(helper, Species == soortje)
  B <- matrix(A[3:8], nrow = 3, ncol = 2, byrow = FALSE)

  # C <- as.data.frame(B)
  # D <- format(C, decimal.mark = ",", nsmall = 1)
  # lay-out goed, maar print helaas niet in de Console

  print(soortje)
  print(B, row.names = FALSE, right = FALSE)

  }
# Take into account the adhoc species (see elsewhere), viz. Aedes albopictus
```