```{r libraries}
library(sf)
library(leaflet)
library(tidyverse)
library(dplyr)
library(vecsets)
library(colorRamps) # for Matlab-like plots

source("./prius2/scripts/helper_functions.R")
```

```{r clear memory}
rm(list = setdiff(ls(), c("read_species_list", "IAS_Cube")))
```

```{r get species list}
species_list <- read_species_list(file_path = "./prius2/temp/",
                                  prius_version = 2)
```

```{r get shapes}
vla_1km <- st_read("./prius/data/spatial/grids/vla_1km.geojson")
Vlaanderen_grenzen <- st_read("./prius/data/spatial/flanders_wgs84.geojson")
Provincies_grenzen <- st_read("./prius2/spatial/provincies2025.geojson") # !! updated
ps_vglrl <- st_read("./prius/data/spatial/ps_vglrl.geojson")
ps_hbtrl_deel <- st_read("./prius/data/spatial/ps_hbtrl_deel.geojson")
```

NOTE: the species cube is (too) heavy to push to the git. This will give an error when running the script. I needed to download it locally (making connection with zenodo within the script was too slow). So maybe best to download the most recent version of the species cube and put it in the folder data/input before running it.

```{r update cube locally}
fistools::download_gdrive_if_missing(gfileID = "154S4vww2G1f0vH7_jt1cZJXeUEmXlZaL",
                                     destfile = "prius2/input/prius2_species_cube.csv",
                                     update_always = TRUE,
                                     email = Sys.getenv("email"))
```

```{r get cube data}
IAS_Cube <- read_csv(file = "./prius2/input/prius2_species_cube.csv") %>% 
  as_tibble()

gc()
```

```{r set time frame}
time.frame.start <- 2015 # !! first year
time.frame.stop  <- 2025 # !! last year (included)
```

```{r}
IAS_Cube <- IAS_Cube %>%
  filter(year >= time.frame.start &
           year <= time.frame.stop) %>%
  filter(specieskey %in% species_list$GBIF_code) %>% 
  filter(eeacellcode %in% vla_1km$CELLCODE)
```

```{r test data completeness}
IAS_Cube_summarise <- IAS_Cube %>% 
  group_by(specieskey) %>% 
  summarise(n_tot = sum(occurrences, na.rm = TRUE), 
            unique_cells = n_distinct(eeacellcode))

cells_per_species <- IAS_Cube_summarise %>% 
  left_join(species_list, by = c("specieskey" = "GBIF_code")) %>% 
  select(specieskey, unique_cells, soort)

not_in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "specieskey")) %>% 
  filter(is.na(n_tot))

write_csv(not_in_cube, "./prius2/temp/taxonkeys_not_in_cube_jas.csv")

in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "specieskey")) %>% 
  filter(!is.na(n_tot))

not_in_cube$soort %in% in_cube$soort

List_species_present <- unique(in_cube$soort)
List_species_not_present <- vsetdiff(unique(species_list$soort) , List_species_present)
write_csv2(cells_per_species, "./prius2/output/distribution_maps/cells_per_species.csv")
write(List_species_present, "./prius2/output/distribution_maps/species_present.txt")
write(List_species_not_present, "./prius2/output/distribution_maps/species_not_present.txt")
```

```{r maps}
# note : colour gradient (matlab-like) over years, as requested by ANB
# note : to save space, legend not included in graphs, but shown in separate fig.

my.cols <- matlab.like(n_distinct(seq(time.frame.start, time.frame.stop)))

for (species_name in unique(in_cube$soort)){
  print(species_name)
  GBIF_codes <- in_cube[which(in_cube$soort==species_name),]$GBIF_code
  print(GBIF_codes)
  IAS_Cube_temp <- IAS_Cube %>%
    filter(specieskey %in% GBIF_codes) %>% 
    group_by(eeacellcode, specieskey) %>%
    summarise(year = as.integer(max(year, na.rm = TRUE)))
  print(IAS_Cube_temp)
  IAS_Cube_1km_spec <- merge(vla_1km,
                             IAS_Cube_temp,
                             by.x = 'CELLCODE',
                             by.y = 'eeacellcode',
                             all.y = TRUE)
  
  temp_plot <- ggplot() +
    geom_sf(data = Vlaanderen_grenzen, fill= "#f0f0f0", size = 0.2) +
    geom_sf(data= ps_vglrl, colour= "#a4e98f", fill="#a4e98f") + 
    geom_sf(data= ps_hbtrl_deel, colour="#a4e98f", fill="#a4e98f") +
    geom_sf(data = Provincies_grenzen, fill= NA, size=0.2) +
    geom_sf(data = IAS_Cube_1km_spec,  aes(colour = year, fill = year),
            stroke = 0) + # only show filling, not lines
    scale_colour_gradientn(colors = my.cols,
                         limits = c(time.frame.start, time.frame.stop)) +
    scale_fill_gradientn(colors = my.cols,
                         limits = c(time.frame.start, time.frame.stop)) +
    theme_void() +
    theme(
      legend.position = "none",
      legend.title = element_blank()
      ) +
    coord_sf()
  
  ggsave(temp_plot, file=paste0(
    "./prius2/output/distribution_maps/", species_name,".png"),
    width = 15.0, height = 5.1, # important for fluent incorporation in report
    units = "cm", dpi = 200)
}
```

```{r legend}
# one-off figure to extract the legend
# based on the last species of the above loop 

ggplot() +
  geom_sf(data = Vlaanderen_grenzen, fill= "#f0f0f0", size = 0.2) +
  geom_sf(data = IAS_Cube_1km_spec,  aes(colour = year, fill = year),
          stroke = 0) +
  scale_colour_gradientn(colors = my.cols,
                         limits = c(time.frame.start, time.frame.stop),
                         breaks = seq(time.frame.start, time.frame.stop, by = 2)) +
  scale_fill_gradientn(colors = my.cols,
                       limits = c(time.frame.start, time.frame.stop),
                       breaks = seq(time.frame.start, time.frame.stop, by = 2)) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.key.width = unit(2, "cm"),
    legend.title = element_blank()
    ) +
    coord_sf()

ggsave(file=paste0("./prius2/output/distribution_maps/",
                   "_legende.png"),
       width = 15.0, height = 5.1,
       units = "cm", dpi = 200)
```