Populate the table with all of the output, for report and Zenodo.

```{r prep packages}
library(tidyverse)
library(readxl)
source("./prius2/scripts/helper_functions.R")
```

```{r prep memory}
# rm(list = ls())
rm(list = setdiff(ls(), c("read_species_list")))
```

```{r species list}
spp.list.raw <- read_species_list(file_path = "./prius2/temp/",
                                  prius_version = 2)
```

```{r some first mutations}
table <- spp.list.raw %>%
  transmute(groep = groep,
            
            GBIF_code = GBIF_code,
            
            soort = soort,
            species = GBIF_canonicalName,
            # GBIF_scientificName     # ditched (redundant met code)
            
            naam_Unielijst = species_wettelijke_naam,
            naam_Unielijst_lijst = species_wettelijke_naam_bron,
            Unielijst = ifelse(is.na(reg), 0, reg),
            
            lijst_rip = ifelse(is.na(rip), 0, rip),
            lijst_dun = ifelse(is.na(dun), 0, dun),
            lijst_vad = ifelse(is.na(vad), 0, vad),
            lijst_hoc = ifelse(is.na(hoc), 0, hoc),
            
            # marien,             # overruled by new env
            # brakwater,          # "
            # zoetwater,          # "
            # terrestrisch,       # "
            
            # natuur,             # overruled by new imp
            # volksgezondheid,    # "
            # veiligheid,         # "
            # infrastructuur,     # "
            # socioeconomisch,    # "
            
            # indam_gem = indamming_gem,        # ditched
            # indam_min = indamming_min,        # "
            # indam_max = indamming_max,        # "
            # indam_std = indamming_stafw,      # "
            # uitroei_gem = uitroeiing_gem,     # "
            # uitroei_min = uitroeiing_min,     # "
            # uitroei_max = uitroeiing_max,     # "
            # uitroei_std = uitroeiing_stafw,   # "
            
            # int_groep           # overruled
            )
```

# MILIEU

```{r populate environment}
env <- read.csv("./prius2/temp/criterium_milieu_v26-02-06.csv") %>% 
  select(-soort) # only keep GBIF_code for matching

table <- table %>% 
  left_join(env, by = "GBIF_code")
```

# IMPACT

```{r}
imp <- read.csv("./prius2/temp/criterium_impact_v26-03-12.csv") %>%
  select(-soort) # only keep GBIF_code for matching

table <- table %>% 
  left_join(imp, by = "GBIF_code")
```

# AANWEZIGHEID

```{r}
aan <- read.csv("./prius2/temp/criterium_aanwezigheid_2026-02-13.csv") %>%
  select(GBIF_canonicalName, aanwezigheid)

table <- table %>% 
  left_join(aan, by = c("species" = "GBIF_canonicalName")) %>% 
  rename(aanwezig_VL = aanwezigheid)
```

# NATURA2000

```{r}
n2k <- read.csv("./prius2/output/occupancy_Natura2000/occupancy_Natura2000.csv") %>%
  select(species,
         N_occ, N_occ_in_N2000,
         X._in_N2000, X._in_HRL, X._in_VRL,
         X._of_N2000, X._of_HRL, X._of_VRL)

table <- table %>% 
  left_join(n2k, by = c("soort" = "species")) %>% 
  rename(hokken_VL = N_occ,
         hokken_N2000 = N_occ_in_N2000,
         percent_in_N2000 = X._in_N2000, 
         percent_in_HRL = X._in_HRL, 
         percent_in_VRL = X._in_VRL,
         promille_van_N2000 = X._of_N2000, 
         promille_van_HRL = X._of_HRL, 
         promille_van_VRL = X._of_VRL)
```

# TOENAME

```{r}
toe <- read.csv("./prius2/output/GAM_outputs_2000_2025_Occupancy/summary4report_2026_03_08_full.csv") %>% 
  select(GBIF_canonicalName, status.vlaanderen, status.natura2000)

table <- table %>% 
  left_join(toe, by = c("species" = "GBIF_canonicalName")) %>% 
  rename(toename_VL = status.vlaanderen,
         toename_N2000 = status.natura2000) %>% 
  mutate(toename_VL = stringr::str_replace(toename_VL, "\\*", ""),
         toename_N2000 = stringr::str_replace(toename_N2000, "\\*", ""))
```

# BUURREGIO'S

```{r}
buu <- read.csv("./prius2/temp/criteria_buurregios_2026-03-08.csv") %>% 
  select(-soort, -reg)

table <- table %>% 
  left_join(buu, by = c("species" = "GBIF_canonicalName"))
```

# BEHEERBAARHEID

```{r}
# ditched
```

# PRIUS-CATEGORIE

```{r}
# prius_groep is temporarily abbreviated to G for ease of scripting
table$G <- NA

# IRR
table$G[is.na(table$G) &
          table$natuur == 0] <- "IRR" # no nature impact
table$G[is.na(table$G) &
          table$zoetwater == 0 & table$terrestrisch == 0] <- "IRR" # purely marine/brackish

# randgevallen : Amerikaanse baars en mummichog
# cf. PrIUS-1 ook tot marien/brakwater gerekend

table$G[table$soort == "Amerikaanse baars"] <- "IRR"
table$G[table$soort == "mummichog"] <- "IRR"

# REL-AFW
table$G[is.na(table$G) &
          table$aanwezig_VL == "afwezig"] <- "REL-AFW"

# REL-AAN-SPO
table$G[is.na(table$G) &
          table$aanwezig_VL == "sporadisch"] <- "REL-AAN-SPO"

table$G[table$soort %in% c("moerasaronskelk",
                           # "zijdeplant",
                           "rosse stekelstaart")] <- "REL-AAN-SPO" # cf. Prius p. 55

# REL-AAN-GEV-BEP
table$G[is.na(table$G) &
          table$hokken_VL < 120] <- "REL-AAN-GEV-BEP" # cf. Prius p. 56

# REL-AAN-GEV-VER-BUI + REL-AAN-GEV-VER-NAT
table$G[is.na(table$G) &
          table$percent_in_N2000 <= 50.0] <- "REL-AAN-GEV-VER-BUI" # cf. Prius p. 57

table$G[is.na(table$G) &
          table$percent_in_N2000 > 50.0] <- "REL-AAN-GEV-VER-NAT" # cf. Prius p. 57

table <- table %>% 
  rename(prius_groep = G)
```

```{r}
write.csv(table, "./prius2/output/final_table_v26-03-21.csv",
          row.names = FALSE)
```