# taxon changes

```{r}
old <- read.csv("./prius2/temp/prius2_list_v25-09-23.csv")
new <- read.csv("./prius2/temp/prius2_list_v26-02-06.csv")
```

```{r}
old.sel <- old[,c("soort", "GBIF_canonicalName", "GBIF_scientificName", "GBIF_code")]
new.sel <- new[,c("soort", "GBIF_canonicalName", "GBIF_scientificName", "GBIF_code")]
```

```{r OLD}
# diff <- anti_join(old.sel, new.sel, by = c("soort", "GBIF_canonicalName"))
# diff2 <- anti_join(old.sel, new.sel, by = c("soort", "GBIF_code"))
# diff3 <- anti_join(old.sel, new.sel, by = c("soort", "GBIF_scientificName"))
```

```{r NEW}
diff <- anti_join(new.sel, old.sel, by = c("soort", "GBIF_canonicalName"))
diff2 <- anti_join(new.sel, old.sel, by = c("soort", "GBIF_code"))
diff3 <- anti_join(new.sel, old.sel, by = c("soort", "GBIF_scientificName"))
```

```{r}
identical(diff, diff2)
identical(diff, diff3)
identical(diff2, diff3)
```

# have the distribution maps changes with the new cube ?

```{r}
library(png)   # install.packages("png") if needed
```

```{r}
spp.to.map <- subset(spp.list.metrics, aanwezigheid != "afwezig")

for (GBIF_canonicalName in spp.to.map[27:143,]$GBIF_canonicalName){
  
  print(GBIF_canonicalName)
  
  path.old <- paste0("./prius2/output/distribution_maps_old_tdot/",
                   GBIF_canonicalName,
                   ".png")
  
  path.new <- paste0("./prius2/output/distribution_maps/",
                   GBIF_canonicalName,
                   ".png")
  
  img1 <- readPNG(path.old)  # returns a numeric array
  img2 <- readPNG(path.new)

  # First check dimensions
  # identical(dim(img1), dim(img2))

  # Then check pixel values
  print(identical(img1, img2))
  # TRUE if every pixel (and channel) is exactly the same
  }

```

