---
title: "TRIAS_indicators"
author: "Jasmijn"
date: '2022-08-17'
output: html_document
---

```{r setup, include=FALSE}
#SETUP
library(tidyverse) # To do data science
library(tidylog) # To provide feedback on dplyr functions
library(progress) # To add progress bars
library(here) # To find files
library(lubridate) # To work with dates
library(rgbif) # To get taxa from publisehd unified checklist
library(sf)# To perform spatial operations
```


```{r cars}
#get alien occurence data
df <- read_csv(
  file = "./data/input/be_species_cube.csv",
  col_types = cols(
    year = col_double(),
    eea_cell_code = col_character(),
    speciesKey = col_double(),
    n = col_double(),
    min_coord_uncertainty = col_double()
  ),
  na = ""
)

#species list prius 
species_list <- read_csv('https://raw.githubusercontent.com/inbo/prius/main/data/input/prius_species_list.csv')

#eea_1km_vlaanderen
vla_1km <- st_read("./data/spatial/grids/vla_1km.geojson")

df <-
  df %>%
  select(-min_coord_uncertainty)

df <-
  df %>%
  rename(obs = n,
         taxonKey = speciesKey)
df <-
  df %>%
  filter(taxonKey %in% species_list$GBIF_code)%>%
  filter(eea_cell_code %in% vla_1km$CELLCODE)%>%
  filter(year>=2000)


#baseline
df_bl <- read_csv(
  file = "https://raw.githubusercontent.com/trias-project/occ-cube-alien/master/data/processed/be_classes_cube.csv",
  col_types = cols(
    year = col_double(),
    eea_cell_code = col_character(),
    classKey = col_double(),
    n = col_double(),
    min_coord_uncertainty = col_double()
  ),
  na = ""
)

df_bl <-
  df_bl %>%
  select(-min_coord_uncertainty)

df_bl <-
  df_bl %>%
  rename(cobs = n)

df_bl <-
  df_bl %>%
  filter(eea_cell_code %in% vla_1km$CELLCODE)%>%
  filter(year>=2000)

```
```{r}
#EEA cells in Natura 2000 area
df_prot_areas <- read_tsv(
  "https://raw.githubusercontent.com/trias-project/indicators/master/data/interim/intersect_EEA_ref_grid_protected_areas.tsv",
  na = ""
)

df_prot_areas <-
  df_prot_areas %>%
  select(
    CELLCODE,
    natura2000
  )%>%
   filter(CELLCODE %in% vla_1km$CELLCODE)
```

```{r}
#Add informative columns

taxon_key <-
  df %>%
  distinct(taxonKey) %>%
  pull()

pb <- progress_bar$new(total = length(taxon_key))

spec_names <- map_df(
  taxon_key,
  function(k) {
    pb$tick()
    name_usage(key = k)$data
  }
) %>%
  select(
    taxonKey = key,
    canonicalName,
    scientificName,
    kingdomKey, classKey
  ) %>%
  mutate(canonicalName = ifelse(
    is.na(canonicalName), scientificName, canonicalName
  ))

spec_names <-
  spec_names %>%
  group_by(canonicalName) %>%
  add_tally() %>%
  ungroup() %>%
  mutate(canonicalName = if_else(n > 1,
                                 scientificName,
                                 canonicalName)) %>%
  select(-c(n, scientificName))

class_key <-
  spec_names %>%
  distinct(classKey) %>%
  filter(!is.na(classKey)) %>%
  pull()
pb <- progress_bar$new(total = length(class_key))

kingdom_class <- map_df(
  class_key,
  function(x) {
    pb$tick()
    name_usage(key = x)$data
  }
) %>%
  select(classKey, class, kingdomKey, kingdom)

# add class
spec_names <-
  spec_names %>%
  left_join(kingdom_class %>%
              distinct(.data$classKey, .data$class),
            by = "classKey"
  )

# add kingdom
spec_names <-
  spec_names %>%
  left_join(kingdom_class %>%
              distinct(.data$kingdomKey, .data$kingdom),
            by = "kingdomKey"
  ) 

spec_names %>% head(10)

spec_names %>%
  filter(is.na(classKey))
```
```{r}
df_xy <-
  df %>%
  distinct(eea_cell_code) %>%
  bind_cols(
    tibble(
      x = unlist(str_extract_all(unique(df$eea_cell_code),
        pattern = "(?<=E)\\d+"
      )),
      y = unlist(str_extract_all(unique(df$eea_cell_code),
        pattern = "(?<=N)\\d+"
      ))
    ) %>%
      mutate_all(as.integer)
  )
```
```{r}
df_xy %>% head()
```

```{r}
df_bl_xy <-
  df_bl %>%
  distinct(eea_cell_code) %>%
  bind_cols(
    tibble(
      x = unlist(str_extract_all(unique(df_bl$eea_cell_code),
        pattern = "(?<=E)\\d+"
      )),
      y = unlist(str_extract_all(unique(df_bl$eea_cell_code),
        pattern = "(?<=N)\\d+"
      ))
    ) %>%
      mutate_all(as.integer)
  )

df_bl_xy %>% head()
```

```{r}
#Add information about presence in protected areas
df <-
  df %>%
  left_join(df_prot_areas,
    by = c("eea_cell_code" = "CELLCODE")
  )

df %>% head()

df_bl <-
  df_bl %>%
  left_join(df_prot_areas,
    by = c("eea_cell_code" = "CELLCODE")
  )

df_bl %>% head()
```


```{r}
#create time series
df_cc <- 
  df %>%
  group_by(taxonKey) %>%
  distinct(eea_cell_code) %>%
  ungroup()

df_begin_year <- 
  df %>%
  group_by(taxonKey) %>%
  summarize(begin_year = min(year))

df_cc <- 
  df_cc %>%
  left_join(df_begin_year, by = "taxonKey") %>%
  select(taxonKey, begin_year, eea_cell_code)

df_cc %>% head()

#create time series per eea_code and species
make_time_series <- function(eea_cell_code, taxonKey, begin_year, last_year ) {
  expand_grid(eea_cell_code = eea_cell_code,
              taxonKey = taxonKey,
              year = seq(from = begin_year, to = last_year))

}

# create timeseries slots
df_ts <- pmap_dfr(df_cc, 
                  .f = make_time_series, 
                  last_year = year(Sys.Date())
)

## Add data

# add occurrence data
df_ts <- 
  df_ts %>%
  left_join(df %>% select(taxonKey, year, eea_cell_code, obs), 
            by = c("taxonKey", "year", "eea_cell_code"))

# add membership to protected areas
df_ts <- 
  df_ts %>%
  left_join(df_prot_areas %>% select(CELLCODE, natura2000),
            by = c("eea_cell_code" = "CELLCODE"))
# add classKey
df_ts <- 
  df_ts %>%
  left_join(spec_names %>% 
              select(taxonKey, classKey), 
            by = "taxonKey")
```
```{r}
#Research effort correction
# add baseline data (at class level) diminished by obs of specific alien taxon
df_ts <- 
  df_ts %>%
  left_join(df_bl %>%
              select(year, eea_cell_code, classKey, cobs),
            by = c("year", "eea_cell_code", "classKey")) %>%
  mutate(cobs = cobs - obs)

# replace NAs with 0
df_ts <-
  df_ts %>%
  replace_na(list(cobs = 0, obs = 0))

df_ts %>% head(n = 30)

df_ts <- 
  df_ts %>%
  mutate(pa_cobs = if_else(cobs > 0, 1, 0),
         pa_obs = if_else(obs > 0, 1, 0))

df_ts <-
  df_ts %>%
  select(taxonKey, 
         year, 
         eea_cell_code, 
         obs, 
         pa_obs, 
         cobs, 
         pa_cobs,
         classKey,
         natura2000)

```
```{r}
#save data
write_tsv(df_ts, 
          file = "./data/intermediate/df_timeseries.tsv", 
          na = ""
)

write_tsv(spec_names,
          file = "./data/intermediate/timeseries_taxonomic_info.tsv",
          na = ""
)
```

