
# Inleiding

Toepassing van het GAM-model op soorten van de PrIUS-lijst.
Zie https://trias-project.github.io/indicators/07_occurrence_indicators_modelling.html .

    3: emerging
    2: potentially emerging
    1: unclear
    0: not emerging

```{r}
library(tidyverse) # To do data science
library(trias)
```

```{r clear memory}
rm(list=ls())
```

```{r}
# PrIUS species list
species_list <- read_csv('./data/input/prius_species_list.csv')
```

```{r}
# read in preprocessing files
df_ts <- read_tsv("./data/intermediate/df_timeseries.tsv", na = "")

# preview
df_ts %>%
  filter(taxonKey == "5219858", # Bv. Muskusrat
    year %in% c(2016, 2017),
    eea_cell_code == "1kmE3924N3102")
```

```{r}
spec_names <- read_tsv(file = here::here("./data/intermediate/timeseries_taxonomic_info.tsv"), na = "") %>%
  select(taxonKey, canonicalName) %>%
  filter(taxonKey %in% df_ts$taxonKey)
```

```{r}
df_ts_compact <- df_ts %>%
  group_by(taxonKey, year, classKey) %>%
  summarise(obs = sum(obs), cobs = sum(cobs), ncells = sum(pa_obs), c_ncells = sum(pa_cobs)) %>%
  ungroup()

df_ts_compact_prot_areas <- df_ts %>%
  filter(natura2000 == TRUE) %>%
  group_by(taxonKey, year, classKey) %>%
  summarise(obs = sum(obs), cobs = sum(cobs), ncells = sum(pa_cobs),  c_ncells = sum(pa_cobs)) %>%
  ungroup()

df_ts_compact <- df_ts_compact %>%
  left_join(spec_names, by = "taxonKey")

df_ts_compact_prot_areas <- df_ts_compact_prot_areas %>%
  left_join(spec_names, by = "taxonKey")
```

```{r}
# Last evaluation year
last_year <- lubridate::year(Sys.Date()) - 2

# First evalution year
first_year <- last_year - 2

# Evaluation years
evaluation_years <- seq(first_year, last_year)
evaluation_years

df_ts_compact <- df_ts_compact %>%
  filter(year <= last_year)

df_ts_compact_prot_areas <- df_ts_compact_prot_areas %>%
  filter(year <= last_year)
```

```{r}
appearing_taxa_to_remove <- df_ts_compact %>%
  group_by(taxonKey) %>%
  summarize(begin_year = min(year)) %>%
  filter(begin_year > min(evaluation_years)) %>%
  pull(taxonKey)

df_ts_compact <- df_ts_compact %>%
  filter(!taxonKey %in% appearing_taxa_to_remove)

df_ts_compact_prot_areas <- df_ts_compact_prot_areas %>%
  filter(!taxonKey %in% appearing_taxa_to_remove)

spec_names <- spec_names %>%
  filter(!taxonKey %in% appearing_taxa_to_remove)
```

```{r decision rules}
# See https://trias-project.github.io/trias/reference/apply_decision_rules.html
# GAM output has priority (below), but these decision rules allow to output em_status for those without GAM output

# Only interested in occupancy
# Can also be done for observations (... y_var = "obs" ...)

em_decision_rules_occupancy_FL <- map_dfr(evaluation_years,
                                          ~ apply_decision_rules(df = df_ts_compact, y_var = "ncells", eval_year = .))

em_decision_rules_occupancy_pa <- map_dfr(evaluation_years,
                                          ~ apply_decision_rules(df = df_ts_compact_prot_areas, y_var = "ncells", eval_year = .))
```

```{r decision rules write output}
em_decision_rules_occupancy_FL_2020 <- em_decision_rules_occupancy_FL %>% 
  filter(year == 2020) %>% 
  left_join(species_list, by= c('taxonKey'='GBIF_code'))

write_csv(em_decision_rules_occupancy_FL_2020, "./data/output/emerging_status/output_decision_rules_occupancy_FL_2020.csv")

em_decision_rules_occupancy_pa_2020 <- em_decision_rules_occupancy_pa %>% 
  filter(year == 2020) %>% 
  left_join(species_list, by= c('taxonKey'='GBIF_code'))

write_csv(em_decision_rules_occupancy_pa_2020, "./data/output/emerging_status/output_decision_rules_occupancy_pa_2020.csv")
```

```{r}
# GAM for occupancy data in all of Flanders

dir_name <- "./data/output/emerging_status"
taxon_keys <- unique(df_ts_compact$taxonKey)
taxon_names <- unique(df_ts_compact$canonicalName)
gam_occupancy_BE <- map2(
  taxon_keys, taxon_names,
  function(t, n) {
    df_key <- df_ts_compact %>%
      filter(taxonKey == t) %>%
      filter(year <= max(evaluation_years))
    class_key <- unique(df_key[["classKey"]])
    if (!is.na(class_key)) {
      apply_gam(
        df = df_key,
        y_var = "ncells",
        eval_years = evaluation_years,
        type_indicator = "occupancy",
        taxon_key = t,
        name = n,
        baseline_var = "c_ncells",
        dir_name = dir_name,
        saveplot = FALSE,
        y_label = "occupancy (km2)"
      )
    } else {
      apply_gam(
        df = df_key,
        y_var = "ncells",
        eval_years = evaluation_years,
        type_indicator = "occupancy",
        taxon_key = t,
        name = n,
        dir_name = dir_name,
        saveplot = FALSE,
        y_label = "occupancy (km2)"
      )
    }
  }
)

names(gam_occupancy_BE) <- taxon_keys

for (tK in unique(df_ts_compact$taxonKey)) {
  tK <- as.character(tK)
  print(tK)
  if (!is.null(gam_occupancy_BE[[tK]]$plot)) {
  
    ##
    ggplot(data = gam_occupancy_BE[[tK]]$output, aes(x = year, y = ncells)) +
    theme_bw() +
    xlab("Jaar") + ylab("# cellen (1-km²)") +
    theme(axis.text = element_text(size = 6), axis.title = element_text(size = 6)) +
    geom_point(color = "black", size = 1) +                                             # Ruwe data
    geom_line(aes(x = .data$year, y = .data$fit), color = "grey50", size = 0.5) +       # De GAM-lijn
    geom_point(aes(x = year, y = fit), shape = 1, size = 1) +                           # Punten op de GAM-lijn
    geom_ribbon(aes(ymax = ucl, ymin = lcl), fill = grey(0.5), alpha = 0.4)             # Fout op de GAM-lijn
    
    ggsave(filename = paste0("./data/output/emerging_status/",
                             first(gam_occupancy_BE[[tK]]$output$canonicalName),
                             "_occupancy_corrected_Flanders.jpeg"),
           width = 7, height = 4, units= "cm")
    ##
    
  }
  else {print('no plot')}
  }

```

```{r}
# GAM for occupancy data in protected areas

dir_name <- "./data/output/emerging_status"
taxon_keys <- unique(df_ts_compact_prot_areas$taxonKey)
taxon_names <- unique(df_ts_compact_prot_areas$canonicalName)
gam_occupancy_pa <- map2(
  taxon_keys, taxon_names,
  function(t, n) {
    df_key <- df_ts_compact_prot_areas %>%
      dplyr::filter(taxonKey == t)
    class_key <- unique(df_key[["classKey"]])
    if (!is.na(class_key)) {
      apply_gam(
        df = df_key,
        y_var = "ncells",
        eval_years = evaluation_years,
        type_indicator = "occupancy",
        taxon_key = t,
        name = n,
        baseline_var = "c_ncells",
        df_title = "Natura2000",
        dir_name = dir_name,
        saveplot = FALSE,
        y_label = "occupancy (km2)"
      )
    } else {
      apply_gam(
        df = df_key,
        y_var = "ncells",
        eval_years = evaluation_years,
        type_indicator = "occupancy",
        taxon_key = t,
        name = n,
        df_title = "Natura2000",
        dir_name = dir_name,
        saveplot = FALSE,
        y_label = "occupancy (km2)"
      )
    }
  }
)

names(gam_occupancy_pa) <- taxon_keys

for (tK in unique(df_ts_compact_prot_areas$taxonKey)) {
  tK <- as.character(tK)
  print(tK)
  if (!is.null(gam_occupancy_pa[[tK]]$plot)) {
    
    ## Zie hoger voor toelichtingen
    ggplot(data = gam_occupancy_pa[[tK]]$output, aes(x = year, y = ncells)) +
      theme_bw() +
      xlab("Jaar") + ylab("# cellen (1-km²)") +
      theme(axis.text = element_text(size = 6), axis.title = element_text(size = 6)) +
      geom_point(color = "black", size = 1) +
      geom_line(aes(x = .data$year, y = .data$fit), color = "grey50", size = 0.5) +
      geom_point(aes(x = year, y = fit), shape = 1, size = 1) +
      geom_ribbon(aes(ymax = ucl, ymin = lcl), fill = grey(0.5), alpha = 0.4)
    
    ggsave(filename = paste0("./data/output/emerging_status/",
                             first(gam_occupancy_pa[[tK]]$output$canonicalName),
                             "_occupancy_corrected_ProtectedAreas.jpeg"),
           width = 7, height = 4, units = "cm")
    ##
  }
  else {print('no plot')}
}
```

```{r}
# Save results GAM

method_em <- gam_occupancy_BE[[1]]$em_summary$method[1]

write_tsv(map_dfr(gam_occupancy_BE, function(x) {x$output}), na = "",
          path = paste0("./data/output/emerging_status/output_GAM_", method_em, "_occupancy_FL.tsv"))

method_em <- gam_occupancy_pa[[1]]$em_summary$method[1]

write_tsv(map_dfr(gam_occupancy_pa, function(x) {x$output}), na = "",
          path = paste0("./data/output/emerging_status/output_GAM_", method_em, "_occupancy_pa.tsv"))

em_GAM_occ_FL <- map_dfr(gam_occupancy_BE, function(x) {x$em_summary})

em_GAM_occ_FL_2020 <- em_GAM_occ_FL %>% 
  filter(year == 2020) %>%
  left_join(species_list, by= c('taxonKey'='GBIF_code'))

write_csv(em_GAM_occ_FL_2020, paste0("./data/output/emerging_status/output_GAM_",
                                     method_em, "_occupancy_FL_2020.csv"))

em_GAM_occ_pa <- map_dfr(gam_occupancy_pa, function(x) {x$em_summary})

em_GAM_occ_pa_2020 <- em_GAM_occ_pa %>% 
  filter(year == 2020) %>%
  left_join(species_list, by= c('taxonKey'='GBIF_code'))

write_csv(em_GAM_occ_pa_2020, paste0("./data/output/emerging_status/output_GAM_",
                                     method_em, "_occupancy_pa_2020.csv"))
```

```{r}
# Make master output

strip_decrules_FL <- em_decision_rules_occupancy_FL_2020 %>% 
  select("taxonKey", "em_status")

strip_decrules_PA <- em_decision_rules_occupancy_pa_2020 %>% 
  select("taxonKey", "em_status")

strip_GAM_FL <- em_GAM_occ_FL_2020 %>% 
  select("taxonKey", "em_status")

strip_GAM_PA <- em_GAM_occ_pa_2020 %>% 
  select("taxonKey", "em_status")

master <- species_list %>% 
  select("Species", "Soort", "GBIF_code") %>% 
  full_join(strip_decrules_FL, by = c("GBIF_code" = "taxonKey")) %>% 
  rename("dec_rules_FL" = "em_status") %>% 
  full_join(strip_decrules_PA, by = c("GBIF_code" = "taxonKey")) %>% 
  rename("dec_rules_PA" = "em_status") %>% 
  full_join(strip_GAM_FL, by = c("GBIF_code" = "taxonKey")) %>%
  rename("GAM_FL" = "em_status") %>% 
  full_join(strip_GAM_PA, by = c("GBIF_code" = "taxonKey")) %>% 
  rename("GAM_PA" = "em_status")

rm(strip_decrules_FL, strip_decrules_PA, strip_GAM_FL, strip_GAM_PA)
write_delim(master, "./data/output/emerging_status/output_em-status_all.csv", delim = ";")
```

