```{r libraries}
library(sf)
library(leaflet)
library(tidyverse)
library(dplyr)
library(vecsets)
```

```{r get species list}
aqua_vs_terr <- read_csv('./data/input/aqua_vs_terr.csv') %>%
  mutate_if(is.character, trimws)
species_list <- read_csv('https://raw.githubusercontent.com/inbo/prius/main/data/input/prius_species_list.csv') #species_list in main branch
species_list <- species_list %>%
  mutate_if(is.character, utf8::utf8_encode)%>%
  mutate_if(is.character, trimws)
```

```{r get shapes}
vla_1km <- st_read("./data/spatial/grids/vla_1km.geojson")
Vlaanderen_grenzen <- st_read("./data/spatial/flanders_wgs84.geojson")
Provincies_grenzen <- st_read("./data/spatial/Provincies.geojson")
Waterlopen <- st_read("data/spatial/Waterlopen.geojson")
ps_vglrl <- st_read("data/spatial/ps_vglrl.geojson")
ps_hbtrl_deel <- st_read("data/spatial/ps_hbtrl_deel.geojson")
#ps_hbtrl_deel <- st_transform(ps_hbtrl_deel, crs=st_crs(vla_1km))
#st_write(ps_hbtrl_deel,  "./data/spatial/ps_hbtrl_deel.geojson")
```

NOTE: the species cube is (too) heavy to push to the git. This will give an error when running the script. I needed to download it locally (making connection with zenodo within the script was too slow). So maybe best to download the most recent version of the species cube and put it in the folder data/input before running it.

```{r get cube data}
IAS_Cube <- read_csv(file = "./data/input/be_species_cube.csv")
                       #"https://zenodo.org/record/6341688/files/be_species_cube.csv?download=1") %>%
                       #"https://zenodo.org/record/5819028/files/be_alientaxa_cube.csv?download=1") %>% 
gc()
IAS_Cube <- IAS_Cube %>%
  filter(year >= 2015) %>% 
  filter(speciesKey %in% species_list$GBIF_code) %>% 
  filter(eea_cell_code %in% vla_1km$CELLCODE)
```

```{r test data completeness}
IAS_Cube_summarise <- IAS_Cube %>% 
  group_by(speciesKey) %>% 
  summarise(n_tot = sum(n, na.rm = TRUE))

not_in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "speciesKey")) %>% 
  filter(is.na(n_tot))

write_csv(not_in_cube, "./data/intermediate/taxonkeys_not_in_cube_jas.csv")

in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "speciesKey")) %>% 
  filter(!is.na(n_tot))

not_in_cube$Soort %in% in_cube$Soort

List_species_present <- unique(in_cube$Soort)
List_species_not_present <- vsetdiff(unique(species_list$Soort) , List_species_present)
write(List_species_present, "./data/output/species_present.txt")
write(List_species_not_present, "./data/output/species_not_present.txt")
```



```{r}
for (species_name in unique(in_cube$Soort)){
  print(species_name)
  GBIF_codes<- in_cube[which(in_cube$Soort==species_name),]$GBIF_code
  print(GBIF_codes)
  IAS_Cube_temp <- IAS_Cube %>%
    filter(speciesKey %in% GBIF_codes)
  print(IAS_Cube_temp)
  IAS_Cube_1km_spec <- merge(vla_1km,
                      IAS_Cube_temp,
                      by.x='CELLCODE',
                      by.y='eea_cell_code',
                      all.y=TRUE)
  
  
  if (aqua_vs_terr[which(aqua_vs_terr$Soort==species_name),]$NICH == "TERR") {
  print('TERR')
  temp_plot<- ggplot() +
  geom_sf(data = Vlaanderen_grenzen, fill= "#f0f0f0", size = 0.2)+ #te activeren indien achterkleur grijs
  geom_sf(data= ps_vglrl, colour= "#a4e98f", fill="#a4e98f") + 
  geom_sf(data= ps_hbtrl_deel, colour="#a4e98f", fill="#a4e98f")+
  #geom_sf(data = Vlaanderen_grenzen) +
  geom_sf(data = Provincies_grenzen, fill= NA, size=0.2) +
  geom_sf(data=IAS_Cube_1km_spec,  colour="red")+
  theme_void() + # Zonder "assen" (coördinaten)
  theme(legend.position="bottom", legend.title = element_blank()) +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))+
  coord_sf()
  } else
  {
    print('AQUA')
    temp_plot<- ggplot() +
  geom_sf(data = Vlaanderen_grenzen, fill ="#f0f0f0", size=0.2) +
  geom_sf(data = Waterlopen, colour= "lightblue")+
  geom_sf(data = Provincies_grenzen, fill=NA, size=0.2) +
  geom_sf(data=IAS_Cube_1km_spec,  colour="red")+
  theme_void() + # Zonder "assen" (coördinaten)
  theme(legend.position="bottom", legend.title = element_blank()) +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))+
  coord_sf()
  }
  
  ggsave(temp_plot, file=paste0("./data/output/spread_maps/", species_name,".png"), width = 15, height = 6.4, units = "cm", dpi=200)
}
```

