```{r libraries}
library(sf)
library(leaflet)
library(tidyverse)
library(dplyr)
library(vecsets)
```

```{r clear memory}
rm(list=ls())
```

```{r get species list}
species_list <- read_csv('./data/input/prius_species_list.csv')
species_list <- species_list %>%
  mutate_if(is.character, utf8::utf8_encode ) %>%
  mutate_if(is.character, trimws)
```

```{r get shapes}
vla_1km <- st_read("./data/spatial/grids/vla_1km.geojson")
#ps_hbtrl_deel <- st_transform(ps_hbtrl_deel, crs=st_crs(vla_1km))
#st_write(ps_hbtrl_deel,  "./data/spatial/ps_hbtrl_deel.geojson")
```

NOTE: the species cube is (too) heavy to push to the git. This will give an error when running the script. I needed to download it locally (making connection with zenodo within the script was too slow). So maybe best to download the most recent version of the species cube and put it in the folder data/input before running it.

```{r get cube data}
IAS_Cube <- read_csv(file = "./data/input/be_species_cube.csv")
                       #"https://zenodo.org/record/6341688/files/be_species_cube.csv?download=1") %>%
                       #"https://zenodo.org/record/5819028/files/be_alientaxa_cube.csv?download=1") %>% 
gc()
IAS_Cube <- IAS_Cube %>%
  filter(year >= 2015) %>% 
  filter(speciesKey %in% species_list$GBIF_code) %>% 
  filter(eea_cell_code %in% vla_1km$CELLCODE)
```

```{r test data completeness}
IAS_Cube_summarise <- IAS_Cube %>% 
  group_by(speciesKey) %>% 
  summarise(n_tot = sum(n, na.rm = TRUE))

not_in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "speciesKey")) %>% 
  filter(is.na(n_tot))

write_csv(not_in_cube, "./data/intermediate/taxonkeys_not_in_cube_jas.csv")

in_cube <- species_list %>% 
  left_join(IAS_Cube_summarise, by = c("GBIF_code" = "speciesKey")) %>% 
  filter(!is.na(n_tot))

not_in_cube$Soort %in% in_cube$Soort

List_species_present <- unique(in_cube$Soort)
List_species_not_present <- vsetdiff(unique(species_list$Soort) , List_species_present)
write(List_species_present, "./data/output/species_present.txt")
write(List_species_not_present, "./data/output/species_not_present.txt")
```

```{r}
keep_all <- data.frame(year = c(2015, 2016, 2017, 2018, 2019, 2020, 2021)) ## Keep all species
keep_all$year <- as.factor(keep_all$year)                                  ## For compatibility with below

for (species_name in unique(in_cube$Soort)){
  print(species_name)
  GBIF_codes<- in_cube[which(in_cube$Soort==species_name),]$GBIF_code
  print(GBIF_codes)
  IAS_Cube_temp <- IAS_Cube %>%
    filter(speciesKey %in% GBIF_codes)
  print(IAS_Cube_temp)
  IAS_Cube_1km_spec <- merge(vla_1km,
                      IAS_Cube_temp,
                      by.x='CELLCODE',
                      by.y='eea_cell_code',
                      all.y=TRUE)
  IAS_Cube_sporadic <- IAS_Cube_1km_spec %>% 
  group_by(year)%>%
  summarize(n=n())
  
  IAS_Cube_sporadic$year <- as.factor(IAS_Cube_sporadic$year)
  
  data <- data.frame(year = c(2015, 2016, 2017, 2018, 2019, 2020, 2021))
  
  data$year <- as.factor(data$year)
  
  x <- merge(data, IAS_Cube_sporadic)
  x <- replace(x, is.na(x), 0)
                  
  temp_plot<- ggplot(data=x, aes(x=year, y=n)) +
  geom_bar(stat="identity")+
  labs(y = expression ("Occupancy in"~km^2))+
  scale_x_discrete(drop = FALSE)
  
  # ggsave(temp_plot, file=paste0("./data/output/absent-sporadic-present/", species_name,".png"), dpi=200)
  
  keep_all <- keep_all %>% 
    left_join(x[,1:2], by = "year") %>% 
    rename(!!species_name:=n)  ## Geef kolom naam van soort (m.o.: gebruik !! := want variabele)
    
}
```

```{r summary across species}
showme <- t(keep_all)             ## Transpose
colnames(showme) <- showme[1,]    ## First row to column names...
showme <- showme[-1,]             ## ... and delete first row
showme <- as.data.frame(showme)

write.csv(showme, "./data/output/absent-sporadic-present/absent-sporadic-present.csv")
```